- hosts: all

  vars:
    home_dir: "/home/vagrant"
    metadata_dir: "{{ home_dir }}/metadata"
    host: "http://localhost"
    pyff_port: "9090"
    pyff_url: "{{ host }}:{{ pyff_port }}"
    sp_port: "9087"
    sp_url: "{{ host }}:{{ sp_port }}"
    idp_1_port: "9088"
    idp_2_port: "9089"
    saas_port: "9091"
    sp_metadata: "{{ home_dir }}/pysaml2/example/sp-wsgi/sp.xml"
    server_cert: /etc/localhost.pem
    server_key: /etc/localhost.key
    frontend_cert: /etc/localhost.pem
    frontend_key: /etc/localhost.key
    backend_cert: /etc/localhost.pem
    backend_key: /etc/localhost.key

  pre_tasks:
    - name: copy localhost cert
      copy: src=localhost.crt dest=/etc/localhost.crt owner=vagrant group=vagrant mode=0755
    - name: copy localhost private key
      copy: src=localhost.key dest=/etc/localhost.key owner=vagrant group=vagrant mode=0755

  roles:
    - {role: pyff, sudo: yes}
    - {role: saas_proxy, sudo: yes}
    - {role: sp, sudo: yes}
    - {role: idps, sudo: yes}
    - {role: integration_test, sudo: yes}


