- hosts: all

  vars:
    home_dir: /home/vagrant
    host: "http:localhost"
    pyff_port: "9090"
    pyff_url: "{{ host }}:{{ pyff_port }}"
    sp_port: "9087"
    sp_url: "{{ host }}:{{ sp_port }}"

  roles:
    - {role: sp, sudo: yes }


