#--- SATOSA Config ---#
HOST: '0.0.0.0'
PORT: 8000
BASE: "https://localhost"
HTTPS: No
PLUGIN_PATH:
  - "plugins"
BACKEND_MODULES:
  - "saml2_backend"
FRONTEND_MODULES:
  - "saml2_frontend"
USER_ID_HASH_SALT: "abcdef"

#--- Server Config ---#
STATIC_DIR: '/static'
LOG_FILE: 'server.log'

# Beaker session configuration
# This session can be configured to use database, file, or memory
SESSION_OPTS:
    session.type: 'memory'
    session.cookie_expires: Yes  # Expire when the session is closed
    session.auto: Yes
