- name: fetch pysaml2 from github
  git:
    repo=https://github.com/its-dirg/pysaml2
    dest={{ pysaml2_dir }}
    version=d355ec58e46786b05e64cc712ad4f2f3bf3c6f9e
    force=yes

- name: Overwrite sp_conf.py
  template:
    src=sp_conf.py.j2
    dest={{ sp_dir }}/sp_conf.py

- name: Overwrite service_conf.py
  template:
    src=service_conf.py.j2
    dest={{ sp_dir }}/service_conf.py

- name: update apt-get
  apt:
    update_cache=yes

- name: install pip
  apt:
    name=python-pip

- name: install python-dev
  apt:
    name=python-dev

- name: install build-essential
  apt:
    name=build-essential

- name: install libffi-dev
  apt:
    name=libffi-dev

- name: install xmlsec1
  apt:
    name=xmlsec1

- name: install daemon
  apt:
    name=daemon

- name: install cryptography
  pip:
    name=cryptography

- name: install pycrypto
  pip:
    name=pycrypto

- name: install example requirements
  pip:
    requirements={{ pysaml2_dir }}/example/requirements.txt

- name: install pysaml2 from local project
  command:
    pip install -e .
    chdir={{ pysaml2_dir }}

- name: start SP
  shell:
    nohup python sp.py -D {{ pyff_url }}/role/idp.ds sp_conf &
    chdir={{ sp_dir }}
  poll: 0