- name: Download pyff docker images
  command: docker pull leifj/pyff

- name: Creates pyff folder
  file: path={{ pyff_dir }} state=directory owner=vagrant group=vagrant mode=0755

- name: create config.yaml
  template: src=mdx.fd.j2
            dest={{ pyff_dir }}/mdx.fd

- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN=asd.se" -days 3650 -keyout {{ pyff_dir }}/{{ key_file }} -out {{ pyff_dir }}/{{ cert_file }} -extensions v3_ca creates={{ pyff_dir }}/{{ cert_file }}

- name: stop containers
  script: stop_containers.sh

- name: start pyff
  command: docker run -e DATADIR=/opt/pyff -v {{ pyff_dir }}:/opt/pyff -p 9090:8080 -d leifj/pyff